import {Palette, ListView, Button} from "std-widgets.slint";

export component PopupMenu {
    in property <[string]> items;
    callback choice(string);

    public function close() {
        self.visible = false;
    }

    Rectangle {
        background: Palette.alternate-background;
        border-radius: 5px;
        width: 100px;
        height: root.height;
        VerticalLayout {
            for item in items: Button{
                text: item;

                clicked => {
                    choice(item);
                }
            }
        }
    }
}
