import { Button, ProgressIndicator, LineEdit, Palette } from "std-widgets.slint";
import { Localization } from "../globals/localization.slint";
import { AppData } from "../globals/app_data.slint";
import { PopupMenu } from "./context_menu.slint";

export component TopPanel {
    callback settings();
    callback on_from_file();
    property <bool> add_song: true;
    
    VerticalLayout {
        spacing: 10px;
        padding: 10px;
        padding-bottom: 5px;
        HorizontalLayout {
            height: 50px;
            spacing: 10px;

            Button {
                icon: @image-url("../../assets/icons/add.svg");
                colorize-icon: true;

                clicked => {
                    if(add_song){
                        popup.visible = true;
                    }
                    else
                    {
                        popup.visible = false;
                    }

                    add_song = !add_song;
                }
            }

            LineEdit {
                placeholder-text: Localization.search;
                font-size: 16px;
                edited(value) => {
                    AppData.searching(value)
                }
            }

            Button {
                icon: @image-url("../../assets/icons/down.svg");
                colorize-icon: true;
                clicked => {
                    AppData.scroll();
                }
            }

            Button {
                icon: @image-url("../../assets/icons/settings.svg");
                colorize-icon: true;
                clicked => {
                    settings()
                }
            }
        }

        ProgressIndicator {
            progress <=> AppData.progress;
        }
    }
    HorizontalLayout {
        alignment: start;
        padding-left: 5px;
        popup := PopupMenu {
            items: ["From File", "From YouTube"];
            visible: false;
            y: 60px;
            z: 100;

            choice(item) => {
                if(item == "From File"){
                    AppData.on_add_song_from_file();
                }
            }
        }
    }
}
